Swann
TheoBrs/plushs-memory pull request #33
Opened 2024-03-25 11:08 UTC by OshidaBCF

2024-03-25 11:22 UTC, TheoBrs requested changes
- Enlever tout le code mort (les "using", fonctions... Tout ce qui est inutilisé)
- Eviter le plus possible les variables publiques -> Utiliser des get/set, récupérer une variable privée à travers une fonction, mettre des variables privées en [SerializeField], ect...
- Revoir les conventions de nommage pour toutes les variables (se servir du fichier texte envoyé par Lilian)

2024-03-25 11:22 UTC, TheoBrs commented on Assets/Scripts/Board/Mouvment.cs
Renommer en "Movement"

2024-03-25 14:24 UTC, TheoBrs requested changes
- Les variables sont toujours toutes en public
- Pas de déplacement

2024-03-25 14:24 UTC, TheoBrs commented on Assets/Scripts/Board/GridElement.cs
> +namespace Board
Pourquoi namespace?

2024-03-25 14:24 UTC, TheoBrs commented on Assets/Scripts/Board/Grid.cs
> +namespace Board
Namespace board à enlever

2024-03-25 14:24 UTC, TheoBrs commented on Assets/Scripts/Board/Grid.cs
> +    public class Grid : MonoBehaviour
Modifier le nom "Grid" pour un nom plus explicite

2024-03-25 14:24 UTC, TheoBrs commented on Assets/Scripts/Character/Entity.cs
> +        _grid = GameObject.Find("WorldPlane");
Pas de Find car pas optimisé et ça peut casser facilement

2024-03-25 14:24 UTC, TheoBrs commented on Assets/Scripts/Gameplay/Turn.cs
Script inutile

2024-03-25 14:24 UTC, TheoBrs commented on Assets/Scripts/Gameplay/Ability.cs
> +    public Ability() {}
Ne sert à rien

2024-03-25 14:24 UTC, TheoBrs commented on Assets/Scripts/Character/Player.cs
> +        // why the "f" in front of ability ? Fake ?
Pas besoin de mettre un commentaire pour ça, ça sert à rien

2024-03-25 14:39 UTC, Firzus requested changes

2024-03-25 14:39 UTC, Firzus commented on .editorconfig
Enlever

2024-03-25 14:39 UTC, Firzus commented on Assets/Prefabs/System/GridCell.prefab
Grid Cell pas dans le bon dossier

2024-03-25 14:39 UTC, Firzus commented on Assets/Scripts/Board/Coord.cs
> +            this.x = x;
this inutile

2024-03-25 14:39 UTC, Firzus commented on Assets/Scripts/Board/Grid.cs
> +        void Update()
code mort

2024-03-25 14:39 UTC, Firzus commented on Assets/Scripts/Board/Movement.cs
> +    // Start is called before the first frame update
enlever les commentaires inutiles par défaut

2024-03-25 14:39 UTC, Firzus commented on Assets/Scripts/Board/Movement.cs
> +    void Update()
la physique dans un fixed update

2024-03-25 14:39 UTC, Firzus commented on Assets/Scripts/Character/Entity.cs
> +    public Coord _currentPos; // Public for Testing
comme tout le reste

2024-03-25 14:39 UTC, Firzus commented on Assets/Scripts/Character/Entity.cs
> +    GameObject _grid;
pourquoi en public ?

2024-03-25 14:39 UTC, Firzus commented on Assets/Scripts/Character/Entity.cs
> +    public void Move(Coord to)
un nom plus explicite que "to"

2024-03-25 14:39 UTC, Firzus commented on Assets/Scripts/Character/Entity.cs
> +        Vector3 newPosition = gridElement.gridElement.transform.position;
gridElement.gridElement ??????????

2024-03-25 14:39 UTC, Firzus commented on Assets/Scripts/Character/Player.cs
> +        if (Input.GetKey(KeyCode.E))
exporter dans une autre fonction

2024-03-25 18:05 UTC, OshidaBCF commented on Assets/Scripts/Gameplay/Turn.cs
Pour l'instant 

Ask kevin

2024-03-25 18:08 UTC, OshidaBCF commented on Assets/Scripts/Board/Coord.cs
> +            this.x = x;
"x" = "x" est ambigu

2024-03-25 18:09 UTC, OshidaBCF commented on Assets/Scripts/Character/Entity.cs
> +    GameObject _grid;
C'est pas public

2024-03-26 10:37 UTC, TheoBrs requested changes
Ne modifie pas ce qui a déjà été fait. Si vraiment tu as besoin tu peux demander, mais normalement il faut pas toucher

2024-03-26 10:37 UTC, TheoBrs commented on Assets/Scripts/Character/Entity.cs
> +    [SerializeField] Stat MaxHP;
Pas besoin de mettre [SerializeField] sur ces deux lignes ici, le Header fait la même chose plus proprement

2024-03-26 10:37 UTC, TheoBrs commented on Assets/Scripts/Character/Entity.cs
> +    public Stat GetMaxHP()
J'avais déjà fait une fonction pour récupérer les valeurs de MaxHP et MaxAP, il faut pas les modifier

2024-03-26 10:37 UTC, TheoBrs commented on Assets/Scripts/Character/Player.cs
> -        _ability1.Damage = 2;
Encore une fois ça sert à rien de modifier ce que j'ai déjà fait, il faut que ça revienne comme avant pour les abilities

2024-03-26 10:37 UTC, TheoBrs commented on Assets/Scripts/Gameplay/Turn.cs
Fonction inutile toujours

2024-03-26 10:37 UTC, TheoBrs commented on Assets/Scripts/Character/Entity.cs
> -    public struct Coord
Pourquoi avoir supprimé ça?

2024-03-26 10:40 UTC, OshidaBCF commented on Assets/Scripts/Character/Entity.cs
> -    public struct Coord
Unused + on a une autre structure Coord plus complete

2024-03-26 10:41 UTC, OshidaBCF commented on Assets/Scripts/Character/Entity.cs
> +    [SerializeField] Stat MaxHP;
J'ignorai ça, on ma dit de tout mettre en privé

2024-03-26 10:46 UTC, OshidaBCF commented on Assets/Scripts/Character/Player.cs
> -        _ability1.Damage = 2;
les variable ne sont pas instancier ducoup crash

J'ai annulé mes changement mais pour l'instant ces ligne seront en commentaire

2024-03-26 14:08 UTC, closed without merging